-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER AS A
JOIN (
        SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
        FROM USED_GOODS_BOARD
        WHERE STATUS LIKE 'DONE'
        GROUP BY WRITER_ID
        HAVING SUM(PRICE) >= 700000
    ) AS B
ON A.USER_ID = B.WRITER_ID
ORDER BY TOTAL_SALES