-- 코드를 입력하세요
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
     ) B
USING (CAR_ID)
WHERE A.START_DATE >= '2022-10-01'
ORDER BY CAR_ID DESC
